version: 0.0

os: linux

files:
  - source: target/spring-boot-web.jar
    destination: target/

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 180
      runas: root
