version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get update && apt-get install -y maven
  build:
    commands:
      - echo "Building the Java Maven project..."
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
