version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo "Building the Java Maven project..."
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
